### ISSUE TITLE
The database username and password in the docker template should be moved to an environment file

### ISSUE THREAD

**Issue by d7oc** [owncloud/docs-server#279]
## WHAT Needs to be Documented?

The page https://doc.owncloud.com/server/next/admin_manual/installation/docker/ contains a template for docker-compose to setup all the stuff required. In general everything which is needed and should be changed is moved to an environment file. This applies to settings like the ownCloud Admin user name and password. The database user name and password is fixed nevertheless and not moved to an environment file. IMHO it would make sense to move that as well to sharpen the awareness that those values should also be changed (even if it's an internal connection).

To sum things up the new template would then look like:

```yaml
version: "3"

volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    container_name: owncloud_server
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=${DATABASE_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${DATABASE_PASSWORD}
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  mariadb:
    image: mariadb:10.5
    container_name: owncloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
```

and the environment would contain example settings for those values:

```shell
cat << EOF > .env
OWNCLOUD_VERSION=10.9
OWNCLOUD_DOMAIN=localhost:8080
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin
DATABASE_USERNAME=owncloud
DATABASE_PASSWORD=owncloud
HTTP_PORT=8080
EOF
```

## WHERE Does This Need To Be Documented (Link)?

https://doc.owncloud.com/server/next/admin_manual/installation/docker/

## WHY Should This Change Be Made?

This change should be done for security reasons as those changes might be overlooked if not part of the env file.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [X] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other
